# Generated by Django 3.0.2 on 2020-03-12 23:53

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('catagory', models.CharField(choices=[('Meat', 'Meat'), ('Seafood', 'Seafood'), ('Veggie', 'Veggie')], default='Meat', max_length=7)),
                ('ingredients', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=20), size=None)),
                ('prep', models.TextField()),
                ('servings', models.SmallIntegerField()),
                ('totalTime', models.SmallIntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'recipes',
                'db_table': 'recipe',
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60)),
                ('rating', models.CharField(choices=[('Great', 'Great'), ('Average', 'Average'), ('Poor', 'Poor')], default='Great', max_length=7)),
                ('comments', models.TextField()),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipe.Recipe')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'reviews',
                'db_table': 'review',
            },
        ),
    ]
