# Generated by Django 3.0.2 on 2020-03-12 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recipe',
            options={'verbose_name': 'recipes'},
        ),
    ]
