# Generated by Django 3.0.2 on 2020-03-12 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0002_auto_20200312_0752'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='review',
            options={'verbose_name': 'reviews'},
        ),
    ]
