# Generated by Django 3.0.2 on 2020-03-12 17:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0003_auto_20200312_0752'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='recipe',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='recipe.Recipe'),
            preserve_default=False,
        ),
    ]
